"""fix some table errors

Revision ID: 0ed077a26c04
Revises: 7edf785b6883
Create Date: 2026-05-31 22:19:24.928974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed077a26c04'
down_revision: Union[str, Sequence[str], None] = '7edf785b6883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('earnings_growth', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('forward_eps', sa.Float(), nullable=True))
    op.alter_column('company', 'recommendation_key',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('company', 'avg_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('company', 'foward_eps')
    op.drop_column('company', 'earning_growth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('earning_growth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('foward_eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('company', 'avg_volume',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('company', 'recommendation_key',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('company', 'forward_eps')
    op.drop_column('company', 'earnings_growth')
    # ### end Alembic commands ###
