"""inital

Revision ID: 7edf785b6883
Revises: 
Create Date: 2026-05-29 18:10:07.013896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edf785b6883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('ticker', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('trailing_pe', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('week52_high', sa.Float(), nullable=True),
    sa.Column('week52_low', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('day50_avg', sa.Float(), nullable=True),
    sa.Column('day200_avg', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('earning_growth', sa.Float(), nullable=True),
    sa.Column('recommendation_key', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('trailing_eps', sa.Float(), nullable=True),
    sa.Column('foward_eps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('price',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=5), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['company.ticker'], ),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('company')
    # ### end Alembic commands ###
